apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: use-dummy-echo
on:
  push:
    branches:
      - main
jobs:
  echo-job:
    steps:
      - name: Completed
        run: echo "done"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
