apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: dummy-echo

on:
  workflow_call:
    inputs:
      message:
          type: string
          required: true
          description: A message to echo
      username:
          type: string
          required: false
          default: anonymous
          description: A username to echo

jobs:
  app1:
    steps:
    - name: Echo message
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
          echo "Message: ${{ inputs.message }}"

    - name: Echo username
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh 
      run: |
        echo "Username: ${{ inputs.username }}"