apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
metadata:
  name: dummy-echo
spec:
  description: >
    A simple reusable workflow that echoes provided input values.

  parameters:
    message:
      type: string
      required: true
      description: A message to echo

    username:
      type: string
      required: false
      default: anonymous
      description: A username to echo

  steps:
    - name: Echo message
      run: |
        echo "Message: ${{ inputs.message }}"

    - name: Echo username
      run: |
        echo "Username: ${{ inputs.username }}"
